# Generated by Django 2.1.1 on 2018-10-09 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('bio', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='person',
            field=models.ManyToManyField(to='collection.Person'),
        ),
    ]
